{
 "title": "Benchmarking DB - Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"mysql_db\"}[1m])) * 100",
     "legendFormat": "MySQL"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"postgres_db\"}[1m])) * 100",
     "legendFormat": "PostgreSQL"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"mysql_db\"} / 1024 / 1024",
     "legendFormat": "MySQL"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"postgres_db\"} / 1024 / 1024",
     "legendFormat": "PostgreSQL"
    }
   ]
  },
  {
   "title": "Query Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_queries{instance=\"MySQL Database\"}[1m]))",
     "legendFormat": "MySQL"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{instance=\"PostgreSQL Database\"}[1m]))",
     "legendFormat": "PostgreSQL"
    }
   ]
  }
 ]
}