global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]
        labels:
          instance: "PostgreSQL Database"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          instance: "Docker Containers"
